name: Validate code
on: pull_request
jobs:
  validate-code:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  build:
    runs-on: ${{ matrix.os }}
    needs: validate-code
    strategy:
      matrix:
        os: [windows-latest]
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run:  |
          npm ci
          npm link
          kopytko new test-app --rokuIP=foo --rokuDevUser=bar --rokuDevPassword=baz --rokuDevId=qux --rokuDevSigningPassword=quux
          rm test-app/node_modules/.bin/kopytko*
          npm ls
      - name: Run build
        run: npm run build --prefix=test-app -- test
